// nlc_vectors.cpp — emit golden test vectors for the RTL decoder testbench.
//
// Encodes a (small synthetic, or real) frame with the reference codec and writes:
//   <out>/bits.hex      compressed bitstream, one byte per line (for $readmemh)
//   <out>/expected.hex  golden decoded RGB[A] bytes, one per line
//   <out>/params.vh     localparams (W,H,NEAR,TILE,WBITS,COLOR,PACK,BPP,CSIZE,OUTN)
//
// The RTL TB ($readmemh's the two .hex files, includes params.vh) drives the
// decoder with `bits` and checks its output equals `expected`, word-for-word.
//
// Build: make -C tools nlc_vectors

#include "nlc_codec.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

static void gen_synth(uint8_t* img, int W, int H, int bpp) {
    // mix of flat / gradient / sharp edges to exercise MED branches + tile widths
    for (int y = 0; y < H; y++) for (int x = 0; x < W; x++) {
        int i = y * W + x;
        int flat = (x < W/3);
        int r = flat ? 64  : (uint8_t)(x * 6 + y * 3);
        int g = flat ? 200 : (uint8_t)(128 + 40 * sin(x * 0.3) + y);
        int b = flat ? 90  : (uint8_t)(x * 4 + 30);
        if ((x % 11) == 0) { r ^= 0x55; g = (g + 70) & 0xff; }   // occasional sharp edge
        img[i*bpp+0] = (uint8_t)r; img[i*bpp+1] = (uint8_t)g; img[i*bpp+2] = (uint8_t)b;
        if (bpp == 4) img[i*bpp+3] = (uint8_t)(255 - x);
    }
}

static void write_hex(const char* path, const uint8_t* buf, size_t n) {
    FILE* f = fopen(path, "w");
    if (!f) { fprintf(stderr, "cannot write %s\n", path); exit(1); }
    for (size_t i = 0; i < n; i++) fprintf(f, "%02x\n", buf[i]);
    fclose(f);
}

int main(int argc, char** argv) {
    int W = 40, H = 8;
    nlc_params p; memset(&p, 0, sizeof(p));
    p.rgb = NLC_RGB888; p.color = NLC_COLOR_YCOCG; p.near_lvl = 0;
    p.pack = NLC_PACK_TILED; p.tile = 16; p.width_bits = 4; p.rice_k = -1;
    const char* out = "/tmp/nlc_vec";
    const char* frame = NULL;
    const char* rawbits = NULL;

    for (int i = 1; i < argc; i++) {
        if      (!strcmp(argv[i],"--w") && i+1<argc) W = atoi(argv[++i]);
        else if (!strcmp(argv[i],"--h") && i+1<argc) H = atoi(argv[++i]);
        else if (!strcmp(argv[i],"--near") && i+1<argc) p.near_lvl = atoi(argv[++i]);
        else if (!strcmp(argv[i],"--tile") && i+1<argc) p.tile = atoi(argv[++i]);
        else if (!strcmp(argv[i],"--color") && i+1<argc) p.color = strcmp(argv[++i],"rgb") ? NLC_COLOR_YCOCG : NLC_COLOR_RGB;
        else if (!strcmp(argv[i],"--pack") && i+1<argc) { const char* v=argv[++i]; p.pack = !strcmp(v,"global")?NLC_PACK_GLOBAL:(!strcmp(v,"rice")?NLC_PACK_RICE:NLC_PACK_TILED); }
        else if (!strcmp(argv[i],"--fmt") && i+1<argc) p.rgb = strcmp(argv[++i],"rgba") ? NLC_RGB888 : NLC_RGBA;
        else if (!strcmp(argv[i],"--out") && i+1<argc) out = argv[++i];
        else if (!strcmp(argv[i],"--frame") && i+1<argc) frame = argv[++i];
        else if (!strcmp(argv[i],"--rawbits") && i+1<argc) rawbits = argv[++i];   // R3: dump the encoded stream as a binary .nlc (display-sim marker)
    }
    p.width = W; p.height = H;
    int bpp = (p.rgb == NLC_RGBA) ? 4 : 3;
    size_t raw = (size_t)W * H * bpp;

    uint8_t* img = (uint8_t*)malloc(raw);
    if (frame) {
        FILE* f = fopen(frame, "rb");
        if (!f || fread(img, 1, raw, f) != raw) { fprintf(stderr, "bad --frame %s (need %zu bytes)\n", frame, raw); return 1; }
        fclose(f);
    } else gen_synth(img, W, H, bpp);

    size_t cap = nlc_max_encoded_size(&p);
    uint8_t* bits = (uint8_t*)malloc(cap);
    int cs = nlc_encode(img, bits, cap, &p);
    if (cs <= 0) { fprintf(stderr, "encode failed (%d)\n", cs); return 1; }

    uint8_t* dec = (uint8_t*)malloc(raw);
    if (nlc_decode(bits, cs, dec, &p) != 0) { fprintf(stderr, "decode failed\n"); return 1; }
    // sanity: software round-trip bound holds before we trust these as golden
    int maxerr = 0; for (size_t i = 0; i < raw; i++) { int d = abs((int)img[i]-(int)dec[i]); if (d>maxerr) maxerr=d; }
    if ((p.near_lvl == 0 && maxerr != 0)) { fprintf(stderr, "golden self-check failed (near0 maxerr=%d)\n", maxerr); return 1; }

    char path[512];
    snprintf(path, sizeof(path), "%s/bits.hex", out);     write_hex(path, bits, cs);
    snprintf(path, sizeof(path), "%s/expected.hex", out); write_hex(path, dec, raw);
    if (rawbits) {
        FILE* rb = fopen(rawbits, "wb");
        if (!rb) { fprintf(stderr, "cannot write %s\n", rawbits); return 1; }
        fwrite(bits, 1, cs, rb); fclose(rb);
    }
    snprintf(path, sizeof(path), "%s/params.vh", out);
    FILE* vh = fopen(path, "w");
    if (!vh) { fprintf(stderr, "cannot write %s\n", path); return 1; }
    fprintf(vh,
        "// auto-generated by tools/nlc_vectors — do not edit\n"
        "localparam VEC_W     = %d;\n"
        "localparam VEC_H     = %d;\n"
        "localparam VEC_NEAR  = %d;\n"
        "localparam VEC_TILE  = %d;\n"
        "localparam VEC_WBITS = %d;\n"
        "localparam VEC_COLOR = %d;  // 1=YCoCg, 0=RGB\n"
        "localparam VEC_PACK  = %d;  // 0=global, 1=tiled, 2=rice\n"
        "localparam VEC_BPP   = %d;\n"
        "localparam VEC_NP    = %d;\n"
        "localparam VEC_CSIZE = %d;  // compressed bytes\n"
        "localparam VEC_OUTN  = %zu; // expected output bytes\n",
        W, H, p.near_lvl, p.tile, p.width_bits, (int)p.color, (int)p.pack, bpp,
        (p.rgb==NLC_RGBA?4:3), cs, raw);
    fclose(vh);

    printf("nlc_vectors: %dx%d %s %s near=%d tile=%d -> %d bytes (ratio %.2f), wrote %s/{bits,expected}.hex, params.vh\n",
           W, H, bpp==4?"rgba":"888", p.color==NLC_COLOR_YCOCG?"ycocg":"rgb", p.near_lvl, p.tile, cs, (double)raw/cs, out);
    free(img); free(bits); free(dec);
    return 0;
}
